# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
   # ==========================================
   # DONGLE MODE (XIAO BLE + Peripheral Halves)
   # ==========================================

   # Dongle (Central)
   - board: seeeduino_xiao_ble
     shield: leeloo_rev2_dongle_xiao
     artifact-name: dongle_leeloo_xiao

   # Left Half (Peripheral for Dongle)
   - board: nice_nano_v2
     shield: leeloo_rev2_left nice_view_adapter nice_view
     cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
     artifact-name: dongle_leeloo_left_peripheral

   # Right Half (Peripheral for Dongle)
   - board: nice_nano_v2
     shield: leeloo_rev2_right nice_view_adapter nice_view
     cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
     artifact-name: dongle_leeloo_right_peripheral

   # ==========================================
   # DIRECT BLUETOOTH MODE (Traditional Split)
   # ==========================================

   # Left Half (Central for Direct BT)
   - board: nice_nano_v2
     shield: leeloo_rev2_left nice_view_adapter nice_view
     artifact-name: ble_leeloo_left_central

   # Right Half (Peripheral for Direct BT)
   - board: nice_nano_v2
     shield: leeloo_rev2_right nice_view_adapter nice_view
     artifact-name: ble_leeloo_right_peripheral

   # ==========================================
   # SETTINGS RESET (For Both Modes)
   # ==========================================

   - board: nice_nano_v2
     shield: settings_reset
     artifact-name: settings_reset_nice_nano
   - board: seeeduino_xiao_ble
     shield: settings_reset
     artifact-name: settings_reset_xiao
